name: Publish DB Backupper Docker Image

on:
  push:
    branches:
      - feature/**
    paths:
      - 'db-backupper/**'
  workflow_call:

jobs:
  push_to_registry:
    uses: ./.github/workflows/.reusable-docker-build-and-push.yml
    with:
      context: ./db-backupper
      image-name: home-db-backupper
    # without this it cannot login to the registry
    secrets: inherit
