name: Publish S3 Backupper Docker Image

on:
  push:
    branches:
      - feature/**
    paths:
      - 's3-backupper/**'
  workflow_call:

jobs:
  push_to_registry:
    uses: ./.github/workflows/.reusable-docker-build-and-push.yml
    with:
      context: ./s3-backupper
      image-name: home-s3-backupper
    # without this it cannot login to the registry
    secrets: inherit
